# Generated by Django 5.1.4 on 2024-12-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0002_anime_genre_userpreference_delete_animecache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('genres', models.JSONField()),
                ('popularity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
