# Generated by Django 5.1.4 on 2024-12-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0003_animecache_remove_userpreference_favorite_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animecache',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='animecache',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='user',
            name='watched_anime',
            field=models.JSONField(default=list),
        ),
    ]
