# Generated by Django 5.1.4 on 2024-12-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0005_remove_user_watched_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_genres',
            field=models.TextField(blank=True),
        ),
    ]
