# Generated by Django 5.1.4 on 2024-12-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_api', '0006_alter_user_preferred_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_anime',
            field=models.TextField(blank=True),
        ),
    ]
